// packages/vue2/src/components/LanguagePicker.vue
<template>
  <select
    :class="className"
    v-model="selected"
    @change="onChange($event)"
  >
    <option v-for="language in languages"
      :key="language.code"
      :value="language.code">
      {{ language.name }}
    </option>
  </select>
</template>

<script>
import { tx } from '@transifex/native';

export default {
  name: 'LanguagePicker',
  props: {
    className: {
      type: String,
    },
  },
  methods: {
    async getLanguages() {
      this.languages = await tx.getLanguages();
    },
    onChange(e) {
      tx.setCurrentLocale(e.target.value);
    },
  },
  mounted() {
    this.getLanguages();
  },
  data() {
    return {
      selected: tx.getCurrentLocale(),
      languages: [],
    };
  },
};
</script>

// packages/react/src/components/LanguagePicker.jsx
import React from 'react';
import PropTypes from 'prop-types';

import { tx } from '@transifex/native';

import useLanguages from '../hooks/useLanguages';

/* Component to render a language picker. Language options will be fetched
  * asynchronously. Accepts props:
  *
  * - className: the CSS class to use on the <select> tag */

export default function LanguagePicker({ className }) {
  const languages = useLanguages();

  return (
    <select
      className={className}
      onChange={(e) => tx.setCurrentLocale(e.target.value)}
    >
      {languages.map(({ name, code }) => (
        <option key={code} value={code}>{name}</option>
      ))}
    </select>
  );
}

LanguagePicker.propTypes = {
  className: PropTypes.string,
};

LanguagePicker.defaultProps = {
  className: '',
};
